export const ObjectsEditinActionType = {
    SET_OBJECT_POSITION: 'SET_OBJECT_POSITION',
    SET_OBJECT_ROTATION: 'SET_OBJECT_ROTATION',
    DELETE_OBJECT: 'DELETE_OBJECT',
    CREATE_OBJECT: 'CREATE_OBJECT',
} as const;
