export const UsersActionType = {
  GET_SELF: 'GET_SELF',
  GET_SELF_SUCCESS: 'GET_SELF_SUCCESS',
  GET_SELF_FAILED: 'GET_SELF_FAILED',

  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
} as const
