export const AreasActionType = {
    GET_MAP_OBJECTS: 'GET_MAP_OBJECTS',
    GET_MAP_OBJECTS_SUCCESS: 'GET_MAP_OBJECTS_SUCCESS',
    GET_MAP_OBJECTS_FAILED: 'GET_MAP_OBJECTS_FAILED',
    UPDATE_BORDER: 'UPDATE_BORDER',
    DELETE_BORDER: 'DELETE_BORDER',
    SELECT_BORDER: 'SELECT_BORDER',
    CREATE_BORDER: 'CREATE_BORDER',
    UPDATE_KIND: 'UPDATE_KIND',
} as const;
