export const PlacesActionType = {
  GET_PLACES: 'GET_PLACES',
  GET_PLACES_SUCCESS: 'GET_PLACES_SUCCESS',
  GET_PLACES_FAILED: 'GET_PLACES_FAILED',

  CHANGE_MY_PLACE: 'CHANGE_MY_PLACE',
  CHANGE_MY_PLACE_SUCCESS: 'CHANGE_MY_PLACE_SUCCESS',
  CHANGE_MY_PLACE_FAILED: 'CHANGE_MY_PLACE_FAILED',
} as const
