export const RoomEditinActionType = {
    EDIT_START: 'EDIT_START',
    EDIT_SUBMIT: 'EDIT_SUBMIT',
    EDIT_CANCEL: 'EDIT_CANCEL',

    EDIT_SUBMIT_SUCCESS: 'EDIT_SUBMIT_SUCCESS',
    EDIT_SUBMIT_FAILED: 'EDIT_SUBMIT_FAILED',

    SELECT_EDIT: 'SELECT_EDIT',
} as const;
