export const RoomEditinActionType = {
  EDIT_START: 'EDIT_START',
  EDIT_SUBMIT: 'EDIT_SUBMIT',
  EDIT_CANCEL: 'EDIT_CANCEL',

  SET_POSITION: 'SET_POSITION',
  SET_ROTATION: 'SET_ROTATION',
  DELETE_PLACE: 'DELETE_PLACE',
  CREATE_PLACE: 'CREATE_PLACE',

  EDIT_SUBMIT_SUCCESS: 'EDIT_SUBMIT_SUCCESS',
  EDIT_SUBMIT_FAILED: 'EDIT_SUBMIT_FAILED',

  SELECT_EDIT: 'SELECT_EDIT',
} as const
